<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mehuls-MacBook-Pro.local" name="com.morningstar.test.SampleTest2" tests="1" failures="1" timestamp="6 Apr 2016 10:38:29 GMT" time="0.001" errors="0">
  <testcase name="LoginApp" time="0.001" classname="com.morningstar.test.SampleTest2">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 1 parameters but the method com.morningstar.test.SampleTest2#LoginApp takes 0">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 1 parameters but the method com.morningstar.test.SampleTest2#LoginApp takes 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1325)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1213)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- LoginApp -->
</testsuite> <!-- com.morningstar.test.SampleTest2 -->
